site_name: 面向计算机系统能力大赛（龙芯杯）的微系统设计与实现（2025春季） | 哈工大（深圳）
copyright: 'Copyright &copy; 2019 - 2025 哈尔滨工业大学（深圳）'
# repo_name: 'HITSZ-COMP2012'
# repo_url: 'https://gitee.com/hitsz-cslab/cpu'

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - mdx_math:
      enable_dollar_delimiter: True
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
  # - mathjaxhelper.js

theme:
  language: 'zh'
  name: material
  features:
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - navigation.tabs
    - navigation.expand
  # favicon: fontawesome/solid/microchip
  icon:
    logo: fontawesome/solid/microchip
    repo: fontawesome/brands/git-alt
  palette:
    - scheme: 'default'
      primary: 'brown'
      accent: 'brown'
      toggle:
        icon: material/weather-night
        name: 切换到夜晚模式
    - scheme: 'slate'
      primary: 'brown'
      accent: 'brown'
      toggle:
        icon: material/weather-sunny
        name: 切换到白天模式

nav:
  - 首页:
    - 实验须知: index.md
    - 开发板使用须知: home/minisys.md
    - Verilog代码规范: home/codingstyle.md
    - ★常见问题汇总: home/problems.md
    - 作业提交说明:
      - ★课程提交要求: home/submit.md
      - 作业系统指南: home/operation.md
  - 实验1：流水线处理器设计:
    - 实验概述: lab2/0-overview.md
    - 实验原理:
      - miniLA指令集: lab2/1-inst_LA.md
      - 功能部件设计: lab2/2-parts.md
      - 数据通路设计: lab2/3-datpth.md
      - 控制单元设计: lab2/4-ctrler.md
      - 单周期CPU时序: lab2/5-timing.md
      - CPU功能验证: lab2/6-verify.md
      - 系统总线: lab2/7-bus.md
      - 接口与外设: lab2/8-peripheral.md
      - Verilog宏定义使用: lab2/9-macros.md
      - 例外与中断 (选): lab2/10-trap.md
      - 流水线概述: lab3/1-pipeline.md
      - 理想流水线: lab3/2-perfectpl.md
      - 指令相关与流水线冒险: lab3/3-hazard.md
      - 数据冒险的处理: lab3/4-handleDH.md
      - 控制冒险的处理: lab3/5-handleCH.md
    - 实验步骤: lab2/11-step.md
    - 实验步骤: lab3/6-step.md
    - 附录：添加约束: lab2/12-constr.md
  - 实验2 分支预测器设计:
    - 控制冒险的处理: lab3/5-handleCH.md
  - 实验3 高速缓存设计:
    - 实验概述: labIII/0-overview.md
    - 实验原理: labIII/1-theory.md
    - 实验步骤: labIII/2-step.md
    - 附加题: labIII/3-extra.md
    - 实验提交: labIII/4-submit.md
  - 实验4 支持AXI接口的微系统设计:
    - 实验概述: lab4/overview.md
    - 实验原理: lab4/theory.md
    - 实验步骤: lab4/step.md
    - 实验提交: lab4/submit.md
    - 附录：Block Design: lab4/bd.md
  - Trace测试说明:
    - 测试机制说明: trace/trace.md
    - 附录1：远程平台使用指南: trace/remote_env.md
    - 附录2：虚拟机使用指南: trace/vm.md
    - 附录3：实验环境部署指南: trace/env_diy.md
  - SoC的下板调试:
    - 方法1：Trace下板调试: verify/trace-debug.md
    - 方法2：FPGA在线调试: verify/online-debug.md
  - FPGA云实验平台使用指南: fpga_cloud/usr_guide.md
